name: Martin's Movies - Prod Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      TMDB_API_ROOT: ${{ secrets.TMDB_API_ROOT }}
      TMDB_API_ACCESS_TOKEN: ${{ secrets.TMDB_API_ACCESS_TOKEN }}
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies & build
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # 4. Upload build to EC2
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".next,public,package.json,ecosystem.config.js"
          target: "~/app"

      # 5. Restart pm2 on EC2 via SSH
      - name: Restart PM2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            npm install --omit=dev
            pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js